In [1]:
%matplotlib inline
import numpy as np
import sklearn
from sklearn import linear_model, metrics
import pandas as pd
from matplotlib import pyplot as plt
from mylibs import transform as tf
from mylibs import resample as rs

### 01. Crie os seguintes arquivos com extensão .py e implemente os métodos definidos para cada um deles:
* transform.py
    - standardize
    - normalize
* resample.py
    - split_k_fold(n_elem, n_splits=3, shuffle=True, seed=0)
    - n_elem - número total de elementos.
    - n_split - número de folds. Mínimo: 2.
    - shuffle - aleatoriza a ordem dos dados (True) ou não (False).
    - seed - determina uma semente para geração de números aleatórios ou não (None).
    - Retorno: 2 arrays (idx_train e idx_test), cada um com n_splits elementos: 
    - um com os índices de treino. Exemplo para n_splits=3, teremos idx_train[0], idx_train[1] e idx_train[2].
    - um com os índices de teste. Exemplo para n_splits=3, teremos idx_test[0], idx_test[1] e idx_test[2].

In [2]:
np.random.seed(0)
x = np.random.rand(20) # 20 valores
x = (x * 100).round(2) # valores até 100
x = np.resize(x, (20, 1))

In [3]:
tf.normalize(x)

array([[0.56025437],
       [0.73661897],
       [0.61748808],
       [0.55612083],
       [0.42766296],
       [0.66316905],
       [0.44239534],
       [0.92379438],
       [1.        ],
       [0.38494966],
       [0.81770005],
       [0.53916269],
       [0.58060413],
       [0.95961844],
       [0.05384208],
       [0.0709062 ],
       [0.        ],
       [0.86104928],
       [0.80339163],
       [0.90068892]])

In [4]:
tf.standardize(x)

array([[-0.11870903],
       [ 0.48434953],
       [ 0.07699507],
       [-0.13284322],
       [-0.5720902 ],
       [ 0.23319593],
       [-0.52171451],
       [ 1.12437442],
       [ 1.38495081],
       [-0.71814345],
       [ 0.761597  ],
       [-0.19082962],
       [-0.04912535],
       [ 1.24687069],
       [-1.85032791],
       [-1.79197909],
       [-2.03443473],
       [ 0.90982474],
       [ 0.71267098],
       [ 1.04536795]])

In [6]:
test, train = rs.slipt_k_fold(20, 5, True, 2)

In [7]:
train

[array([ 2,  8,  6, 19, 15,  4, 16, 12,  9,  1,  0,  7, 14, 17,  3, 18]),
 array([13, 11, 10,  5, 15,  4, 16, 12,  9,  1,  0,  7, 14, 17,  3, 18]),
 array([13, 11, 10,  5,  2,  8,  6, 19,  9,  1,  0,  7, 14, 17,  3, 18]),
 array([13, 11, 10,  5,  2,  8,  6, 19, 15,  4, 16, 12, 14, 17,  3, 18]),
 array([13, 11, 10,  5,  2,  8,  6, 19, 15,  4, 16, 12,  9,  1,  0,  7])]

In [8]:
test

[array([13, 11, 10,  5]),
 array([ 2,  8,  6, 19]),
 array([15,  4, 16, 12]),
 array([9, 1, 0, 7]),
 array([14, 17,  3, 18])]

### Carregando Dataset

In [19]:
data = pd.read_csv('winequality-red.csv', delimiter=';')
data.shape

(1599, 12)

In [20]:
data.sample(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1455            6.5             0.900         0.00             1.6      0.052   
788            10.0             0.560         0.24             2.2      0.079   
355             6.7             0.750         0.01             2.4      0.078   
338            12.4             0.490         0.58             3.0      0.103   
433            12.3             0.390         0.63             2.3      0.091   
68              9.3             0.320         0.57             2.0      0.074   
820             7.0             0.685         0.00             1.9      0.099   
1198            7.7             0.260         0.26             2.0      0.052   
107             6.2             0.630         0.31             1.7      0.088   
1340            7.5             0.510         0.02             1.7      0.084   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1455                  9.0                  17.0  0.99467  3.50       0.63   
788                  19.0                  58.0  0.99910  3.18       0.56   
355                  17.0                  32.0  0.99550  3.55       0.61   
338                  28.0                  99.0  1.00080  3.16       1.00   
433                   6.0                  18.0  1.00040  3.16       0.49   
68                   27.0                  65.0  0.99690  3.28       0.79   
820                   9.0                  22.0  0.99606  3.34       0.60   
1198                 19.0                  77.0  0.99510  3.15       0.79   
107                  15.0                  64.0  0.99690  3.46       0.79   
1340                 13.0                  31.0  0.99538  3.36       0.54   

      alcohol  quality  
1455     10.9        6  
788      10.1        6  
355      12.8        6  
338      11.5        6  
433       9.5        5  
68       10.7        5  
820       9.7        5  
1198     10.9        6  
107       9.3        5  
1340     10.5        6

In [21]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [23]:
test, train = rs.slipt_k_fold(data.shape[0], 5, True, 3)

In [24]:
test

[array([ 147,  937,  877, 1000,   73,   31,  266, 1403,  263, 1491,  293,
         112, 1246,  592, 1417,    4, 1503,  221,  837, 1083, 1402,  157,
          69,  730,  692,  175,  593, 1018,  984, 1116,  554, 1264, 1381,
         290,   83, 1077, 1270, 1493,  137,  288,  199, 1373, 1107,  745,
         720,   16,  869, 1568,   70,   85,  677,  597, 1237, 1087,  475,
        1511,  719,   61,  515, 1521,  393,  790,  204,  216, 1565, 1286,
         487, 1327,  615, 1454, 1518,  229,  402, 1295, 1598, 1314,  317,
           3,  371, 1117, 1588, 1437,   46,  471,  154,  746,  635,  565,
        1513,  809, 1380,  897,   37,   50, 1567,  268,  304,  743, 1597,
         477, 1158,  409,  416, 1371, 1249, 1370,  170,  103, 1410, 1031,
        1426,  969, 1223,  250, 1465,  751,  168,  752,  197, 1307,  328,
         562,  500,  322,  632,  895, 1422, 1569, 1065,   65,  321, 1173,
         669,  350,  948, 1481, 1068,  464,  608, 1318, 1128, 1475, 1386,
         981,  148, 1305,  675,  264, 

In [33]:
train

[array([ 606,  362,  533, ...,  968,  952, 1273]),
 array([ 147,  937,  877, ...,  968,  952, 1273]),
 array([ 147,  937,  877, ...,  968,  952, 1273]),
 array([ 147,  937,  877, ...,  968,  952, 1273]),
 array([ 147,  937,  877, ...,  305, 1350,  196])]